POST http://localhost:8080/api/v1/assignees
Content-Type: application/json

{
    "prename": "Ana Cristina",
    "name": "Franco da Silva",
    "email": "ana-cristina.franco-da-silva@iste.uni-stuttgart.de"
}
###

GET http://localhost:8080/api/v1/assignees/1

###

POST http://localhost:8080/api/v1/todos
Content-Type: application/json

{
"title": "A shorter title",
"description": "A potentially longer description",
"assigneeIdList": [10],
"dueDate": 1633940572720
}
###
GET http://localhost:8080/api/v1/todos/11

###
PUT http://localhost:8080/api/v1/todos/1
Content-Type: application/json

{
    "title": "A larger title",
    "description": "A potentially longer description",
    "finished": false,
    "assigneeIdList": [1],
    "dueDate": 1933940572720
}
###
GET http://localhost:8080/api/v1/todos