name: Dependabot Alerts to Issues

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Sonntags um Mitternacht

# WICHTIG: Diese Berechtigungen sind ESSENTIELL
permissions:
  contents: read
  security-events: read
  issues: write

jobs:
  convert-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Process Dependabot alerts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # API-Aufruf mit korrekten Headern
          response=$(curl -s \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts?state=open")

          # Debug-Ausgabe
          echo "API Response:"
          echo "$response" | jq .

          # Verarbeitung der Alerts
          echo "$response" | jq -c '.[]' | while read -r alert; do
            title=$(echo "$alert" | jq -r '.security_advisory.summary? // "Unknown vulnerability"')
            package=$(echo "$alert" | jq -r '.dependency.package.name? // "unknown-package"')
            url=$(echo "$alert" | jq -r '.html_url? // ""')

            echo "Creating issue for: $package - $title"

            # Issue erstellen
            curl -s -X POST \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "$(jq -n \
                --arg title "[Dependabot] $package: $title" \
                --arg body "**Package:** $package\n\n**Alert URL:** $url" \
                '{title:$title, body:$body, labels:["security","dependabot"]}')" \
              "https://api.github.com/repos/${{ github.repository }}/issues"
            
            sleep 1  # Rate Limit vermeiden
          done