name: Dependabot Alerts to Issues

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Sonntags um Mitternacht

permissions:
  security-events: read
  issues: write

jobs:
  convert-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Process alerts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # API-Aufruf mit korrekten Headern
          response=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts?state=open")

          # Debug-Ausgabe der Rohantwort
          echo "API Response:"
          echo "$response" | jq .

          # Verarbeitung mit korrektem JSON-Pfad
          echo "$response" | jq -c '.[]' | while read -r alert; do
            title=$(echo "$alert" | jq -r '.security_advisory.summary // "Unbekannte Schwachstelle"')
            package=$(echo "$alert" | jq -r '.dependency.package.name // "Unbekanntes Paket"')
            url=$(echo "$alert" | jq -r '.html_url // ""')

            echo "Erstelle Issue für: $title ($package)"
            
            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -d "$(jq -n \
                --arg title "[Dependabot] $title ($package)" \
                --arg body "Sicherheitslücke in $package\n\nDetails: $url" \
                '{title:$title, body:$body, labels:["security"]}')" \
              "https://api.github.com/repos/${{ github.repository }}/issues"
          done