name: Dependabot Alerts to Issues

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Sonntags um Mitternacht

permissions:
  security-events: read
  issues: write

jobs:
  convert-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Get alerts and create issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install jq if needed
          sudo apt-get install -y jq

          # Fetch alerts
          alerts=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts?state=open")

          echo "$alerts" | jq -c '.[]' | while read -r alert; do
            title=$(echo "$alert" | jq -r '.security_advisory.summary')
            package=$(echo "$alert" | jq -r '.dependency.package.name')
            url=$(echo "$alert" | jq -r '.html_url')

            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -d "$(jq -n \
                --arg title "[Dependabot] $title ($package)" \
                --arg body "Vulnerability in $package\n\nDetails: $url" \
                '{title:$title, body:$body}')" \
              "https://api.github.com/repos/${{ github.repository }}/issues"
          done